//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrAppAPI
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Appointment
    {
        [Key]
        public int Id_Appointment { get; set; }
        public int Id_User { get; set; }
        public string Clinic { get; set; }
        public string Doctor { get; set; }
        public string AppointmentTime { get; set; }
        public string CreationTime { get; set; }
        public Nullable<int> Id_Doc { get; set; }
        public string DRAVAILABLE { get; set; }
    
        public virtual User User { get; set; }
    }
}
