//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrAppAPI
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class doctor
    {
        [Key]
        public int id_doc { get; set; }
        public Nullable<int> Id_User { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string specialty { get; set; }
    
        public virtual User User { get; set; }
    }
}
